export type IFDTag =
  | "ProcessingSoftware"
  | "SubfileType"
  | "OldSubfileType"
  | "ImageWidth"
  | "ImageHeight"
  | "BitsPerSample"
  | "Compression"
  | "PhotometricInterpretation"
  | "Thresholding"
  | "CellWidth"
  | "CellLength"
  | "FillOrder"
  | "DocumentName"
  | "ImageDescription"
  | "Make"
  | "Model"
  | "StripOffsets"
  | "Orientation"
  | "SamplesPerPixel"
  | "RowsPerStrip"
  | "StripByteCounts"
  | "MinSampleValue"
  | "MaxSampleValue"
  | "XResolution"
  | "YResolution"
  | "PlanarConfiguration"
  | "PageName"
  | "XPosition"
  | "YPosition"
  | "GrayResponseUnit"
  | "ResolutionUnit"
  | "PageNumber"
  | "TransferFunction"
  | "Software"
  | "ModifyDate"
  | "Artist"
  | "HostComputer"
  | "Predictor"
  | "WhitePoint"
  | "PrimaryChromaticities"
  | "HalftoneHints"
  | "TileWidth"
  | "TileLength"
  | "SubIFD"
  | "InkSet"
  | "TargetPrinter"
  | "ThumbnailOffset"
  | "ThumbnailLength"
  | "YCbCrCoefficients"
  | "YCbCrSubSampling"
  | "YCbCrPositioning"
  | "ReferenceBlackWhite"
  | "ApplicationNotes"
  | "Rating"
  | "RatingPercent"
  | "Copyright"
  | "PixelScale"
  | "IPTC-NAA"
  | "IntergraphMatrix"
  | "ModelTiePoint"
  | "SEMInfo"
  | "ModelTransform"
  | "PhotoshopSettings"
  | "ExifOffset" // EXIF SubIFD
  | "ICC_Profile"
  | "GeoTiffDirectory"
  | "GeoTiffDoubleParams"
  | "GeoTiffAsciiParams"
  | "GPSInfo" // GPS
  | "ImageSourceData"
  | "XPTitle"
  | "XPComment"
  | "XPAuthor"
  | "XPKeywords"
  | "XPSubject"
  | "GDALMetadata"
  | "GDALNoData"
  | "PrintIM"
  | "DNGVersion"
  | "DNGBackwardVersion"
  | "UniqueCameraModel"
  | "LocalizedCameraModel"
  | "ColorMatrix1"
  | "ColorMatrix2"
  | "CameraCalibration1"
  | "CameraCalibration2"
  | "ReductionMatrix1"
  | "ReductionMatrix2"
  | "AnalogBalance"
  | "AsShotNeutral"
  | "AsShotWhiteXY"
  | "BaselineExposure"
  | "BaselineNoise"
  | "BaselineSharpness"
  | "LinearResponseLimit"
  | "CameraSerialNumber"
  | "DNGLensInfo"
  | "ShadowScale"
  | "DNGPrivateData"
  | "MakerNoteSafety"
  | "CalibrationIlluminant1"
  | "CalibrationIlluminant2"
  | "RawDataUniqueID"
  | "OriginalRawFileName"
  | "OriginalRawFileData"
  | "AsShotICCProfile"
  | "AsShotPreProfileMatrix"
  | "CurrentICCProfile"
  | "CurrentPreProfileMatrix"
  | "ColorimetricReference"
  | "SRawType"
  | "PanasonicTitle"
  | "PanasonicTitle2"
  | "CameraCalibrationSig"
  | "ProfileCalibrationSig"
  | "ProfileIFD"
  | "AsShotProfileName"
  | "ProfileName"
  | "ProfileHueSatMapDims"
  | "ProfileHueSatMapData1"
  | "ProfileHueSatMapData2"
  | "ProfileToneCurve"
  | "ProfileEmbedPolicy"
  | "ProfileCopyright"
  | "ForwardMatrix1"
  | "ForwardMatrix2"
  | "PreviewApplicationName"
  | "PreviewApplicationVersion"
  | "PreviewSettingsName"
  | "PreviewSettingsDigest"
  | "PreviewColorSpace"
  | "PreviewDateTime"
  | "RawImageDigest"
  | "OriginalRawFileDigest"
  | "ProfileLookTableDims"
  | "ProfileLookTableData"
  | "TimeCodes"
  | "FrameRate"
  | "TStop"
  | "ReelName"
  | "OriginalDefaultFinalSize"
  | "OriginalBestQualitySize"
  | "OriginalDefaultCropSize"
  | "CameraLabel"
  | "ProfileHueSatMapEncoding"
  | "ProfileLookTableEncoding"
  | "BaselineExposureOffset"
  | "DefaultBlackRender"
  | "NewRawImageDigest"
  | "RawToPreviewGain"
  | "DepthFormat"
  | "DepthNear"
  | "DepthFar"
  | "DepthUnits"
  | "DepthMeasureType"
  | "EnhanceParams"
  | "CalibrationIlluminant3"
  | "CameraCalibration3"
  | "ColorMatrix3"
  | "ForwardMatrix3"
  | "IlluminantData1"
  | "IlluminantData2"
  | "IlluminantData3"
  | "ProfileHueSatMapData3"
  | "ReductionMatrix3"
  | "RGBTables";

export const IFD_TAG_NAME_BY_TAG_ID: Readonly<{ [tagNumber: number]: IFDTag }> = Object.freeze({
  0x000b: "ProcessingSoftware",
  0x00fe: "SubfileType",
  0x00ff: "OldSubfileType",
  0x0100: "ImageWidth",
  0x0101: "ImageHeight",
  0x0102: "BitsPerSample",
  0x0103: "Compression",
  0x0106: "PhotometricInterpretation",
  0x0107: "Thresholding",
  0x0108: "CellWidth",
  0x0109: "CellLength",
  0x010a: "FillOrder",
  0x010d: "DocumentName",
  0x010e: "ImageDescription",
  0x010f: "Make",
  0x0110: "Model",
  0x0111: "StripOffsets",
  0x0112: "Orientation",
  0x0115: "SamplesPerPixel",
  0x0116: "RowsPerStrip",
  0x0117: "StripByteCounts",
  0x0118: "MinSampleValue",
  0x0119: "MaxSampleValue",
  0x011a: "XResolution",
  0x011b: "YResolution",
  0x011c: "PlanarConfiguration",
  0x011d: "PageName",
  0x011e: "XPosition",
  0x011f: "YPosition",
  0x0122: "GrayResponseUnit",
  0x0128: "ResolutionUnit",
  0x0129: "PageNumber",
  0x012d: "TransferFunction",
  0x0131: "Software",
  0x0132: "ModifyDate",
  0x013b: "Artist",
  0x013c: "HostComputer",
  0x013d: "Predictor",
  0x013e: "WhitePoint",
  0x013f: "PrimaryChromaticities",
  0x0141: "HalftoneHints",
  0x0142: "TileWidth",
  0x0143: "TileLength",
  0x014a: "SubIFD",
  0x014c: "InkSet",
  0x0151: "TargetPrinter",
  0x0201: "ThumbnailOffset",
  0x0202: "ThumbnailLength",
  0x0211: "YCbCrCoefficients",
  0x0212: "YCbCrSubSampling",
  0x0213: "YCbCrPositioning",
  0x0214: "ReferenceBlackWhite",
  0x02bc: "ApplicationNotes",
  0x4746: "Rating",
  0x4749: "RatingPercent",
  0x8298: "Copyright",
  0x830e: "PixelScale",
  0x83bb: "IPTC-NAA",
  0x8480: "IntergraphMatrix",
  0x8482: "ModelTiePoint",
  0x8546: "SEMInfo",
  0x85d8: "ModelTransform",
  0x8649: "PhotoshopSettings",
  0x8769: "ExifOffset",
  0x8773: "ICC_Profile",
  0x87af: "GeoTiffDirectory",
  0x87b0: "GeoTiffDoubleParams",
  0x87b1: "GeoTiffAsciiParams",
  0x8825: "GPSInfo",
  0x935c: "ImageSourceData",
  0x9c9b: "XPTitle",
  0x9c9c: "XPComment",
  0x9c9d: "XPAuthor",
  0x9c9e: "XPKeywords",
  0x9c9f: "XPSubject",
  0xa480: "GDALMetadata",
  0xa481: "GDALNoData",
  0xc4a5: "PrintIM",
  0xc612: "DNGVersion",
  0xc613: "DNGBackwardVersion",
  0xc614: "UniqueCameraModel",
  0xc615: "LocalizedCameraModel",
  0xc621: "ColorMatrix1",
  0xc622: "ColorMatrix2",
  0xc623: "CameraCalibration1",
  0xc624: "CameraCalibration2",
  0xc625: "ReductionMatrix1",
  0xc626: "ReductionMatrix2",
  0xc627: "AnalogBalance",
  0xc628: "AsShotNeutral",
  0xc629: "AsShotWhiteXY",
  0xc62a: "BaselineExposure",
  0xc62b: "BaselineNoise",
  0xc62c: "BaselineSharpness",
  0xc62e: "LinearResponseLimit",
  0xc62f: "CameraSerialNumber",
  0xc630: "DNGLensInfo",
  0xc633: "ShadowScale",
  0xc634: "DNGPrivateData",
  0xc635: "MakerNoteSafety",
  0xc65a: "CalibrationIlluminant1",
  0xc65b: "CalibrationIlluminant2",
  0xc65d: "RawDataUniqueID",
  0xc68b: "OriginalRawFileName",
  0xc68c: "OriginalRawFileData",
  0xc68f: "AsShotICCProfile",
  0xc690: "AsShotPreProfileMatrix",
  0xc691: "CurrentICCProfile",
  0xc692: "CurrentPreProfileMatrix",
  0xc6bf: "ColorimetricReference",
  0xc6c5: "SRawType",
  0xc6d2: "PanasonicTitle",
  0xc6d3: "PanasonicTitle2",
  0xc6f3: "CameraCalibrationSig",
  0xc6f4: "ProfileCalibrationSig",
  0xc6f5: "ProfileIFD",
  0xc6f6: "AsShotProfileName",
  0xc6f8: "ProfileName",
  0xc6f9: "ProfileHueSatMapDims",
  0xc6fa: "ProfileHueSatMapData1",
  0xc6fb: "ProfileHueSatMapData2",
  0xc6fc: "ProfileToneCurve",
  0xc6fd: "ProfileEmbedPolicy",
  0xc6fe: "ProfileCopyright",
  0xc714: "ForwardMatrix1",
  0xc715: "ForwardMatrix2",
  0xc716: "PreviewApplicationName",
  0xc717: "PreviewApplicationVersion",
  0xc718: "PreviewSettingsName",
  0xc719: "PreviewSettingsDigest",
  0xc71a: "PreviewColorSpace",
  0xc71b: "PreviewDateTime",
  0xc71c: "RawImageDigest",
  0xc71d: "OriginalRawFileDigest",
  0xc725: "ProfileLookTableDims",
  0xc726: "ProfileLookTableData",
  0xc763: "TimeCodes",
  0xc764: "FrameRate",
  0xc772: "TStop",
  0xc789: "ReelName",
  0xc791: "OriginalDefaultFinalSize",
  0xc792: "OriginalBestQualitySize",
  0xc793: "OriginalDefaultCropSize",
  0xc7a1: "CameraLabel",
  0xc7a3: "ProfileHueSatMapEncoding",
  0xc7a4: "ProfileLookTableEncoding",
  0xc7a5: "BaselineExposureOffset",
  0xc7a6: "DefaultBlackRender",
  0xc7a7: "NewRawImageDigest",
  0xc7a8: "RawToPreviewGain",
  0xc7e9: "DepthFormat",
  0xc7ea: "DepthNear",
  0xc7eb: "DepthFar",
  0xc7ec: "DepthUnits",
  0xc7ed: "DepthMeasureType",
  0xc7ee: "EnhanceParams",
  0xcd31: "CalibrationIlluminant3",
  0xcd32: "CameraCalibration3",
  0xcd33: "ColorMatrix3",
  0xcd34: "ForwardMatrix3",
  0xcd35: "IlluminantData1",
  0xcd36: "IlluminantData2",
  0xcd37: "IlluminantData3",
  0xcd39: "ProfileHueSatMapData3",
  0xcd3a: "ReductionMatrix3",
  0xcd3b: "RGBTables",
});
